### ISSUE TITLE
I want to install it but get this error

### ISSUE THREAD

**Issue by shoaibjilanigeniteam** [MaartenStaa/gameanalytics-php#1]
The "fxp/composer-asset-plugin" plugin requires composer-plugin-api 1.0.0, this
_WILL_ break in the future and it should be fixed ASAP (require ^1.0 for example
).
Loading composer repositories with package information
Installing dependencies (including require-dev)
Your requirements could not be resolved to an installable set of packages.

  Problem 1
    - The requested package php-http/adapter-implementation could not be found i
n any version, there may be a typo in the package name.
  Problem 2
    - php-http/discovery v0.6.4 requires puli/composer-plugin ~1.0.0-beta8 -> no
 matching package found.
    - php-http/discovery v0.6.3 requires puli/composer-plugin ~1.0.0-beta8 -> no
 matching package found.
    - php-http/discovery v0.6.2 requires puli/composer-plugin ~1.0.0-beta8 -> no
 matching package found.
    - php-http/discovery v0.6.1 requires puli/composer-plugin ~1.0.0-beta8 -> no
 matching package found.
    - php-http/discovery v0.6.0 requires puli/composer-plugin 1.0.0-beta8 -> no
matching package found.
    - Installation request for php-http/discovery ^0.6 -> satisfiable by php-htt
p/discovery[v0.6.0, v0.6.1, v0.6.2, v0.6.3, v0.6.4].

I installed the guzzle6-adapter also but it installed from its command of 
composer require php-http/guzzle6-adapter
but on this folder I cannot install gameanalytics-php from adding your package in composer.json or can you guide how we can use it on yii or independently.

**Comment by MaartenStaa** [comment]
I have published a new release, v2.0, which should resolve this. I relied on php-http/adapter-implementation which is now obsolete. I'm now using [php-http/client-implementation](http://docs.httplug.io/).
